### ISSUE TITLE
Valid Token failed

### ISSUE THREAD

**Issue by ashishWaghmare** [girishsv1986/file_sync#1]
I did get token by running server
http://0.0.0.0:8080/file
{
    "created": "2019-01-29T09:55:32.828243+00:00",
    "file_name": "first_file",
    "token": "UznuFZEuHl",
    "user_name": "ashish"
}

----------FILE OPERATIONS MENU----------
1. File operations
2. Exit
Enter your choice: 1
Enter file token: UznuFZEuHl
Validating file token ...

Invalid file token.

**Comment by girishsv1986** [comment]
@ashishWaghmare : Please confirm, you have updated APPLICATION_HOST constant value with your web server IP.
README.md "To Run" section is updated with this additional step.

**Comment by girishsv1986** [comment]
I assume, updating APPLICATION_HOST value fixed the issue and steps are documented for same
